- project:
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-lower-constraints
        - openstack-tox-cover
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-lower-constraints
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - lib-forward-testing
      - lib-forward-testing-python3
      - periodic-stable-jobs
      - openstack-python36-jobs
    post:
      jobs:
        - openstack-tox-cover
